[versions]
agp = "8.3.1"
compileSdk = "34"
minSdk = "28"
targetSdk = "34"
ndk = "26.2.11394342"
androidx-activity = "1.8.2"
androidx-core = "1.12.0"
androidx-datastore = "1.1.0-beta02"
androidx-hilt = "1.2.0"
androidx-lifecycle = "2.7.0"
androidx-media = "1.7.0"
androidx-navigation = "2.7.7"
androidx-paging = "3.2.1"
androidx-room = "2.6.1"
androidx-test-core = "1.5.0"
androidx-test-espresso = "3.5.1"
androidx-test-junit = "1.1.5"
androidx-test-runner = "1.5.2"
androidx-test-truth = "1.5.0"
cachefix = "3.0.1"
compose-bom = "2024.03.00"
compose-compiler = "1.5.11"
compose-lint = "1.3.1"
coroutines = "1.8.0"
dmach-externals = "3.1.0"
dagger = "2.51"
gradle-versions = "0.51.0"
javaVersion = "17"
kortholt = "3.1.0"
kotlin = "1.9.23"
kotlin-collections = "0.3.7"
kotlin-serialization = "1.6.3"
ktlint = "1.2.1"
ktlint-compose = "0.3.12"
ktlint-gradle = "12.1.0"
ksp = "1.9.23-1.0.19"
leakcanary = "2.13"
mockito-core = "5.11.0"
mockito-kotlin = "5.2.1"
robolectric = "4.11.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint-gradle = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
cachefix = { id = "org.gradle.android.cache-fix", version.ref = "cachefix" }
gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }

[libraries]
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidx-hilt" }
androidx-hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-media = { module = "androidx.media:media", version.ref = "androidx-media" }
androidx-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-paging-common = { module = "androidx.paging:paging-common-ktx", version.ref = "androidx-paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "androidx-paging" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "androidx-room" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-truth = { module = "androidx.test.ext:truth", version.ref = "androidx-test-truth" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-lint = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "compose-lint" }
compose-material = { module = "androidx.compose.material3:material3" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
compose-ui-testmanifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android" }
coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
dmach-externals = { module = "com.github.simonnorberg:dmach-externals", version.ref = "dmach-externals" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
kortholt = { module = "net.simno.kortholt:kortholt", version.ref = "kortholt" }
kotlin-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-collections" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
ktlint-compose = { module = "io.nlopez.compose.rules:ktlint", version.ref = "ktlint-compose" }
leakcanary-plumber = { module = "com.squareup.leakcanary:plumber-android", version.ref = "leakcanary" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-core" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
